apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:{{ kube_version }}
    command:
    - /hyperkube
    - proxy
    #- --master={% for node in groups['master'] %}https://{{ node }}{% if not loop.last %},{% endif %}{% endfor %}
    
    - --master=https://{{ groups['master'][0] }}:{{ kube_master_port }}
    - --kubeconfig={{ kube_config_dir }}/node.kubeconfig
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: {{ kube_config_dir }}
      name: etc-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: {{ kube_config_dir }}
    name: etc-kubernetes
